DIR=aiohttp_security_session_
DIR=managed_attrs
DIR=term_app_
DIR=webscrap_
DIR=stdtools_
DIR=aiohttp_remake_
DIR=deco_meta_
DIR=aiohttp_security_
CUR_TARGET=main

all: ${CUR_TARGET}
clean: ${CUR_TARGET}_clean

${CUR_TARGET}:
	# py ${DIR}/${CUR_TARGET}
	${MAKE} --quiet -B -C ${DIR}