#!/usr/bin/env bash

EXTENSIONS=(.py .pyc)
ARGUMENTS=("$@")

if [ -n "${ARGUMENTS[0]}" ] && [ ! -e "${ARGUMENTS[0]}" ]; then
  for extension in "${EXTENSIONS[@]}"; do
    if [ -e "${ARGUMENTS[0]}$extension" ]; then
      ARGUMENTS[0]="${ARGUMENTS[0]}$extension"
      break
    fi
  done
fi

python3 "${ARGUMENTS[@]}"
