#! /usr/bin/env python 
"""
This is to enable the usage
    py some_file
as a short form of
    python some_file.py
"""

import sys
from pathlib import Path
from subprocess import run

EXT = [".py", ".pyc"]

def main(args: list[str]) -> None:
    """
    All The magic is here
    """
    if len(args) == 1:
        file, sargs = "", ""
    else:
        file, *args = args[1:]
        if not file.endswith(EXT[0]):
            for ext in EXT:
                if (mod := Path(file + ext)).exists():
                    file = str(mod)
                    break

        sargs = ('"' + '" "'.join(args) + '"') if args else ''
    try:
        cmd_args = f'{file} {sargs}' if sargs else file
        out = run(f"python {cmd_args}", shell=True).returncode
    except BaseException:
        sys.exit(-1 if file == "" else 0)
    else:
        sys.exit(0 if file == "" else out)


if __name__ == "__main__":
    main(sys.argv)
