"""Added Product Table

Revision ID: 43384e14dfc1
Revises: b7f12ecee880
Create Date: 2023-05-24 19:12:18.950678

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "43384e14dfc1"
down_revision = "b7f12ecee880"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("pid", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("pid"),
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
