"""Added Order Table

Revision ID: 5688a83419d7
Revises: 43384e14dfc1
Create Date: 2023-05-24 19:12:34.901274

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5688a83419d7"
down_revision = "43384e14dfc1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("oid", sa.Integer(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pid"],
            ["products.pid"],
        ),
        sa.ForeignKeyConstraint(
            ["uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
