
"""Empty Alembic Revision

Revision ID: f3cc4e3164ef
Revises: 
Create Date: 2023-05-24 19:11:49.091363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3cc4e3164ef'
down_revision = None
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

