def application(env, start_response):
    # env contains all the request information from REQUEST_METHOD
    #   to custom headers as HTTP_<header_name> eg HTTP_API_KEY: <value>
    # start_response is a function used to start response as the of
    #   the body is generated by the rest of the function. It takes in
    #   the status eg "201 Accepted" and a list of two valued tuples being
    #   the headers of the response
    items = ((str(name), str(value)) for name, value in env.items())
    # I am returning the headers back to the sender.
    start_response("200 OK", [("Content-Type", "text/html"), *items])
    # print(f'Env: {env}')
    # print(f'StartResponse: {start_response}')
    # This function has to return a list of byte-string as the body of the response
    return [b"WSGI hello!"]
